### PR TITLE
Unique users

### PR DESCRIPTION
**Pull request by simon-gridex**

### CODE REVIEW

**Comment by zsp00** [comment]
So early to start submitting code

**Comment by zsp00** [comment]
When will the Ethereum chain start? In addition, can a few GDX flowers be rewarded?

**Comment by zsp00** [comment]
When will the Ethereum chain be deployed? Also, can you tip me GDX coins?

**Review by maxwellboltz — APPROVED** [review]

**Comment by zsp00** [comment]
@simon-gridex address:0x1918a2aA2698f9d29EbFE175eDE86F2b3bEF337a

**Pull request merged**
